version: "2"
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: reactive
      TZ: 'America/Sao_Paulo'
    volumes:
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql"