micronaut:
  application:
    name: reactive
netty:
  default:
    allocator:
      max-order: 3
kafka:
  producers:
    default:
      executor: io
  bootstrap:
    servers:
      - localhost:8097
      - localhost:8098
      - localhost:8099